### ISSUE TITLE
cargo test readme fails locally

### ISSUE THREAD

**Issue by m4b** [m4b/scroll#39]
@luser when i do cargo test I see readme failures with:

```
failures:

---- README.md - std__io (line 130) stdout ----
error: extern location for scroll does not exist: /home/m4b/projects/scroll/target/debug/libscroll.rlib

error[E0463]: can't find crate for `scroll`
 --> README.md:131:1
  |
2 | extern crate scroll;
  | ^^^^^^^^^^^^^^^^^^^^ can't find crate

thread 'README.md - std__io (line 130)' panicked at 'couldn't compile the test', librustdoc/test.rs:333:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- README.md - _::Scroll___cast_some_magic::Deriving_ (line 86) stdout ----
error: extern location for scroll does not exist: /home/m4b/projects/scroll/target/debug/libscroll.rlib

error[E0463]: can't find crate for `scroll`
 --> README.md:88:1
  |
3 | extern crate scroll;
  | ^^^^^^^^^^^^^^^^^^^^ can't find crate

thread 'README.md - _::Scroll___cast_some_magic::Deriving_ (line 86)' panicked at 'couldn't compile the test', librustdoc/test.rs:333:13

---- README.md - _::Scroll___cast_some_magic::Overview (line 37) stdout ----
error: extern location for scroll does not exist: /home/m4b/projects/scroll/target/debug/libscroll.rlib

error[E0463]: can't find crate for `scroll`
 --> README.md:38:1
  |
2 | extern crate scroll;
  | ^^^^^^^^^^^^^^^^^^^^ can't find crate

thread 'README.md - _::Scroll___cast_some_magic::Overview (line 37)' panicked at 'couldn't compile the test', librustdoc/test.rs:333:13

---- README.md - Advanced_Uses (line 184) stdout ----
error: extern location for scroll does not exist: /home/m4b/projects/scroll/target/debug/libscroll.rlib

error[E0463]: can't find crate for `scroll`
 --> README.md:185:1
  |
2 | extern crate scroll;
  | ^^^^^^^^^^^^^^^^^^^^ can't find crate

thread 'README.md - Advanced_Uses (line 184)' panicked at 'couldn't compile the test', librustdoc/test.rs:333:13

---- README.md - std__io (line 154) stdout ----
error: extern location for scroll does not exist: /home/m4b/projects/scroll/target/debug/libscroll.rlib

error[E0463]: can't find crate for `scroll`
 --> README.md:155:1
  |
2 | extern crate scroll;
  | ^^^^^^^^^^^^^^^^^^^^ can't find crate

thread 'README.md - std__io (line 154)' panicked at 'couldn't compile the test', librustdoc/test.rs:333:13


failures:
    README.md - Advanced_Uses (line 184)
    README.md - _::Scroll___cast_some_magic::Deriving_ (line 86)
    README.md - _::Scroll___cast_some_magic::Overview (line 37)
    README.md - std__io (line 130)
    README.md - std__io (line 154)

test result: FAILED. 0 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out

test readme_test ... FAILED

failures:

---- readme_test stdout ----
Running `"rustdoc" "--verbose" "--test" "-L" "/home/m4b/projects/scroll/target/debug" "-L" "/home/m4b/projects/scroll/target/debug/deps" "--extern" "scroll=/home/m4b/projects/scroll/target/debug/libscroll.rlib" "README.md"`
thread 'readme_test' panicked at 'Failed to run rustdoc tests on README.md!', tests/readme.rs:27:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    readme_test
```

I don't really understand what this means? But the CI seems to be passing; if I update the README, do I have do something special to get the tests to pass or?

**Comment by m4b** [comment]
I had to:

1. remove the rust annotation to the code fence
2. add no_test to the code fence

on the offending README example in order to get tests passing on the derive example; this is pretty undesirable state of affairs, but I don't have time to figure this out right now

**Comment by m4b** [comment]
So I disabled the readme tests in bb214ae1fd2ce4cc7bd4efe3c1fbb8f2739dc5d2, because I don't know what's wrong; @luser if you get a chance/have some time, and want the readme tests still running, would you mind looking into this?

**Comment by luser** [comment]
While looking at the external docs issue I found a link to [doc-comment](https://github.com/GuillaumeGomez/doc-comment) which has a clever workaround for this so I inlined the concept and it works nicely! (Thanks @GuillaumeGomez!)

https://github.com/m4b/scroll/pull/66

**Comment by GuillaumeGomez** [comment]
And since `#[cfg(doctest)]` has been stabilised (in 1.40), you'll be able to do:

```rust
#[cfg(doctest)]
doctest!("../README.md");
```

Don't hesitate to come back to me if you find any issue. :)

**Comment by m4b** [comment]
Cool! Since it looks like @luser fix works for now, we’ll probably wait a few rustc cycles to adopt 1.40 since other upstream deps have much lower rustc requirements? Though I guess the test doesn’t effect the required rustc for building when used as a dep?

**Comment by GuillaumeGomez** [comment]
It doesn't indeed.

**Comment by m4b** [comment]
Awesome this is closed thank you @luser and will upgrade to doctest when the time comes : D

Thanks everyone !
